@extends('layouts.master')

@section('title')
    Documentation
@endsection

@section('contentContainer')
    <div class="documentationTitle">
        <h3>Documentation</h3>
    </div>

    <div class="postNowPosts">
        <strong><p>The PostNow website satisfied the following requirements:</p></strong>
        <p>1. All pages must have a navigation menu, either across the top of the page or down the left or right column.</p>
        <p>2. The home page must display all posts. Only posts should be displayed, not comments.</p>
        <p>3. Next to each post there should a number indicating how many comments are there for this post.</p>
        <p>4. From the home page, click on a post will bring up the comments page. The comments page for a post should contain that post and all comments for that post.</p>
        <p>5. The home page must display a form for the user to create a new post. Each post should contain a title, a message, a date, an icon, and a user’s name (the user is not required to login, they can simply enter their name in the post form). All posts can have the same icon. When creating a new post, user must enter the title, message, and user’s name. Date can either be entered or generated by the system. After a new post is successfully created, it should redirect back to the home page.</p>
        <p>6. Users can edit posts. After a post is edited, the comments page for that post is displayed.</p>
        <p>7. Users can delete posts. When user deletes a post, the comments for that post should also be deleted.</p>
        <p>8. Users can add comments to a post. A comment must have a message and a user, but no title.</p>
        <p>9. Users can delete comments.</p>
        <p>10. There is a page that lists all unique users that have made a post (i.e. a user is only displayed once no matter how many posts this user has made). Clicking on the user should display all posts made by that user.</p>
        <p>11. There is a most recent page, which shows only the posts that have been made in the last 7 days.</p>
    </div>

    <div class="postNowPosts">
        <strong><p>PostNow Technical Requirements:</p></strong>
        <p>1. Implemented using laravel.</p>
        <p>2. Database should be implemented via raw SQL and executed through Laravel's database class.</p>
        <p>3. An SQL file should be used to create tables and insert initial data. There should be enough initial data to thoroughly test the retrieval, update, and deletion functionalities you have implemented.</p>
        <p>4. Proper security measures have been implemented.</p>
        <p>5. Template inheritance has been properly used.</p>
        <p>6. Consistent, readable and descriptive names for files, functions and variables have been used.</p>
        <p>7. Correct indenting and spacing of code has been correctly executed.</p>
        <p>8. Comments have been used for each function along with a short description.</p>
    </div>

    <div class="postNowPosts">
        <strong><p>PostNow extras:</p></strong>
        <p>1. Documentation created to describe the tasks completed along with approaches.</p>
        <p>2. Enitity Relationship Diagram created for the database.</p>
    </div>
@endsection('contentContainer')